quiz_app/routes.py
from flask import (
    Blueprint,
    render_template as render,
    flash,
    redirect,
    url_for,
    request
)
from . import models
from .extentions import db
from flask_login import (
    logout_user,
    login_required,
    login_user,
    current_user
)
from random import shuffle
from werkzeug.utils import secure_filename
from os.path import join, dirname
from add_questions import (
    load_questions,
    add_to_db
)
from flask import current_app
from .constants import ADD_QUESTIONS

main = Blueprint("main", __name__)

@main.route("/")
def index():
    return render("index.html")

@main.route("/login", methods=["GET", "POST"])
def login():
    if not current_user.is_anonymous:
        flash("You are already logged in, logout to login with another account", "info")
        return redirect(url_for("main.index"))
    if request.method == "POST":
        data = request.form.to_dict()
        user = models.User.query.filter_by(
            name=data["name"],
            is_admin=True if "is_admin" in data.keys() else False
        ).first()
        if user is not None and user.verify_password(data["password"]):
            login_user(user)
            flash("logged in successfully", "success")
            return redirect(url_for("main.index"))
        else:
            flash("user's name or password is wrong", "warning")
    return render("login.html")


@main.route("/logout")
@login_required
def logout():
    logout_user()
    flash("logged out", "info")
    return redirect(url_for("main.index"))
    

@main.route("/register", methods=["GET", "POST"])
def register():
    if not current_user.is_anonymous:
        flash("You are already logged in, logout to login with another account", "info")
        return redirect(url_for('main.index'))
    if request.method == "POST":
        data = request.form.to_dict()
        name = data["name"]
        password = data["password"]
        if models.User.query.filter_by(name=name).first() is not None:
            flash("user with this username already exists", "info")
            return redirect(url_for("main.register"))
        user = models.User(
            name=name,
            is_admin=False
        )
        user.set_password(data["password"])
        db.session.add(user)
        db.session.commit()
        flash("register complete", "success")
        return redirect(url_for("main.login"))
    return render("register.html")


@main.route("/add", methods=["GET", "POST"])
@login_required
def add_questions():
    if request.method == "POST":
        data = request.form.to_dict()
        for i in range(1, ADD_QUESTIONS+1):
            question = models.Question(
                question=data[f"q{i}"],
                option1=data[f"q{i}o1"],
                option2=data[f"q{i}o2"],
                option3=data[f"q{i}o3"],
                option4=data[f"q{i}o4"],
                correct_option=data[f"q{i}c"][0].upper(),
                creator_id=current_user.id
            )
            db.session.add(question)
            db.session.commit()
        else:
            flash("your questions added successfully", "success")
    return render(
        "add_questions.html",
        questions=ADD_QUESTIONS,
        show=True if models.Question.query.filter_by(creator_id=current_user.id).first() is None else False
    )


@main.route("/quiz", methods=["GET", "POST"])
@login_required
def quiz():
    if request.method == "POST":
        data = request.form.to_dict()
        qset = current_user.question_set
        total_questions = len(
            models.Question.query.filter_by(
                question_set_id = qset
            ).all()
        )
        result = models.Result(
            total_number=total_questions,
            correct=0,
            not_attempt=0,
            incorrect=0,
            user_id=current_user.id
        )
        for i in range(1, total_questions+1):
            q, o = data.get(f"q{i}", None), data.get(f"q{i}o", None)
            question = models.Question.query.filter_by(
                id=q,
                correct_option=o,
                verified=True
            ).first()
            if question is not None:
                result.correct += 1
            else:
                result.incorrect += 1
        result.not_attempt = result.total_number-(result.correct+result.incorrect)
        db.session.add(result)
        db.session.commit()
        flash("quiz complete", "success")
        return redirect(url_for("main.result"))
    print("abcdefg", current_user, current_user.question_set)
    questions = models.Question.query.filter_by(
        question_set_id = current_user.question_set
    ).all()
    shuffle(questions)
    return render(
        "quiz.html",
        questions=questions,
        show=True if models.Result.query.filter_by(user_id=current_user.id).first() is None else False
    )


@main.route("/result")
@login_required
def result():
    res = models.Result.query.filter_by(
        user_id=current_user.id
    ).all()
    if res is not None:
        return render(
            "result.html", 
            results=res, 
            user=current_user
        )
    else:
        return render(
            "result.html",
            results=models.Result(
                user_id=current_user.id,
                total_number=0,
                correct=0,
                incorrect=0,
                not_attempt=0
            ), user=current_user
        )


@main.route("/leaderboard")
@login_required
def leaderboard():
    res = models.Result.query.order_by(
        models.Result.correct.desc()
    ).all()
    return render("leaderboard.html", results=res)


@main.route("/admin")
@login_required
def admin():
    if current_user.is_admin:
        # {title: {link: link_of_btn(to_be_redirected), btn_text: text}}
        panel_options = {
            "Upload Questions": {
                "link": url_for("main.admin_upload_questions"),
                "btn-text": "Upload"
            },
            "Verify & Add Questions": {
                "link": url_for("main.admin_add_questions"),
                "btn-text": "Add"
            },
            "Create SETs": {
                "link": url_for("main.admin_create_set"),
                "btn-text": "Create"
            },
            "Show SETs": {
                "link": url_for("main.admin_show_sets"),
                "btn-text": "Show"
            },
            "Distribute SETs": {
                "link": url_for("main.admin_distribute_sets"),
                "btn-text": "Distribute"
            },
            "Get Results": {
                "link": url_for("main.admin_results"),
                "btn-text": "Get"
            }
        }
        return render(
            "admin/admin.html",
            panel_options = panel_options
        )
    else:
        flash("You are not an admin, so you can't access this", "warning")
        return redirect(url_for("main.index"))

@main.route("/admin/results")
@login_required
def admin_results():
    if current_user.is_admin:
        res = models.Result.query.all()
        return render("admin/result.html", results=res)
    else:
        flash("You are not an admin, so you can't access this portal", "warning")
        return redirect(url_for('main.index'))

@main.route("/admin/add-questions", methods=["GET", "POST"])
@login_required
def admin_add_questions():
    if current_user.is_admin:
        if request.method == "POST":
            data, changed = request.form, 0
            for i in data:
                if data[i] == "on":
                    qno = int(i[1:])
                    q = models.Question.query.filter_by(id=qno).first()
                    q.verified = True
                    db.session.commit()
                    changed += 1
            flash(f"{changed} questions added.", "success")
        qs = models.Question.query.filter_by(verified=False).all()
        return render("admin/add_questions.html", questions=qs)
    else:
        flash("You are not an admin, so you can't access this page", "warning")
        return redirect(url_for("main.index"))

@main.route("/admin/upload", methods=["GET", "POST"])
@login_required
def admin_upload_questions():
    if current_user.is_admin:
        if request.method == "POST":
            if 'qFile' not in request.files:
                flash('No file part')
                return redirect(request.url)
            file = request.files['qFile']
            if (fname:=file.filename) == '':
                flash('No selected file')
                return redirect(request.url)
            if file and ('.' in fname and fname.rsplit('.', 1)[1].lower() in ["csv"]):
                flocation = join(dirname(__file__), "..", "upload_files", "questions.csv")
                file.save(flocation)
                qbank = load_questions(flocation)
                q_added = add_to_db(
                    qbank=qbank,
                    app=current_app,
                    db=db,
                    verbose=False
                )
                flash(f"{q_added} questions added successfully", "success")

        return render("admin/upload_questions.html")
    else:
        flash("You are not an admin, so you can't access this page", "warning")
        return redirect(url_for("main.index"))

@main.route("/admin/create_set", methods=["GET", "POST"])
@login_required
def admin_create_set():
    if current_user.is_admin:
        if request.method == "POST":
            data, added = request.form, 0
            set_name = data.get("set_name", "abcd")
            q_set = models.QuestionSet(
                name=set_name
            )
            db.session.add(q_set)
            db.session.commit()
            for i in data:
                if data[i] == "on":
                    qno = int(i[1:])
                    q = models.Question.query.filter_by(id=qno).first()
                    q.question_set_id = q_set.id
                    db.session.commit()
                    added += 1

templates/add_questions.html
{% extends 'layout.html' %}

{% block title %}Add Questions{% endblock %}

{% block body %}
  <form method="post" action="{{ url_for('main.add_questions') }}">
  <h1 class="text-center">
    Add Questions
  </h1>
  <br><br>
  {% for i in range(1, questions+1) %}
  <div class="mb-3">
    <label for="InputQuestion{{ i }}" class="form-label">Question {{ i }}*</label>
    <input type="text" class="form-control" id="InputQuestion{{ i }}" name="q{{ i }}" placeholder="Question {{ i }}" required autofocus>
  </div>
  <div class="row">
    <div class="col">
      <input type="text" class="form-control" placeholder="Option 1" name="q{{ i }}o1" required>
    </div>
    <div class="col">
    <input type="text" class="form-control" placeholder="Option 2" name="q{{ i }}o2" required>
  </div>
  <div class="col">
    <input type="text" class="form-control" placeholder="Option 3" name="q{{ i }}o3" required>
  </div>
  <div class="col">
    <input type="text" class="form-control" placeholder="Option 4" name="q{{ i }}o4" required>
  </div>
  </div>
  <br>
  <select class="form-select" name="q{{ i }}c" required>
    <option selected disabled value=''>Choose Correct Option</option>
    <option value="A">A</option>
    <option value="B">B</option>
    <option value="C">C</option>
    <option value="D">D</option>
  </select>
  <br>
  {% endfor %}
  <br>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
    <label class="form-check-label" for="exampleCheck1">I confirmed.</label>
  </div>
  <br><br><br>
  <button type="submit" class="btn btn-primary w-100" {% if not show %}onclick="question_already_added(); return false"{% endif %}>Submit</button>
</form>
<script>
  const question_already_added = () => {
    alert("You already added questions, wait until administrator not allow you to further add questions")
  }
</script>
{% endblock %}

templates/admin_add_questions.html
{% extends 'layout.html' %}

{% block title %}Admin{% endblock %}

{% block body %}
<div class="row mt-5">
  <h1 class="text-center">
    Add Questions
  </h1>
</div>
<div class="row mt-3">
  <form action="{{ url_for('main.admin_add_questions') }}" method="post">
    <table class="table">
    <thead>
      <tr>
        <th scope="col">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" onchange="checkAll(this)">
            <label class="form-check-label" for="flexCheckDefault">
              Select All
            </label>
          </div>
        </th>
        <th scope="col">Questions</th>
        <th scope="col">Option1</th>
        <th scope="col">Option2</th>
        <th scope="col">Option3</th>
        <th scope="col">Option4</th>
        <th scope="col">Correct Option</th>
        <th scope="col">Creator</th>
      </tr>
    </thead>
    <tbody>
    {% for q in questions %}
    <tr>
      <th scope="row">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" name="q{{q.id}}">
        </div>
      </th>
      <th>{{ q.question }}</th>
      <th>{{ q.option1 }}</th>
      <th>{{ q.option2 }}</th>
      <th>{{ q.option3 }}</th>
      <th>{{ q.option4 }}</th>
      <th>{{ q.correct_option }}</th>
      <th>{{ q.creator.name }}</th>
    </tr>
    {% endfor %}
    </tbody>
  </table>
    <br>
    <button type="submit" class="btn btn-primary w-100">Add</button>
  </form>
</div>

<script>
  let checkboxes = document.querySelectorAll("input[type = 'checkbox']");
  const checkAll = (myCheckBox)=>{
    let chkd = myCheckBox.checked;
    checkboxes.forEach((checkboxe)=>{
      checkboxe.checked = chkd;
    });
  };
</script>
{% endblock %}

templates/admin_result.html
{% extends 'layout.html' %}

{% block title %}Admin{% endblock %}

{% block body %}
  <h1 class="text-center">
    Results
  </h1>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Total Questions</th>
      <th scope="col">Not Attempt</th>
      <th scope="col">Correct</th>
      <th scope="col">Incorrect</th>
      <th scope="col">Total Marks</th>
    </tr>
  </thead>
  <tbody>
    {% for result in results %}
    <tr>
      <th scope="row">{{ result.user.id }}</th>
      <td>{{ result.user.name }}</td>
      <td>{{ result.total_number }}</td>
      <td>{{ result.not_attempt }}</td>
      <td>{{ result.correct }}</td>
      <td>{{ result.incorrect }}</td>
      <td>{{ result.correct }}/{{ result.total_number }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

templates/admin_upload_questions.html
{% extends 'layout.html' %}

{% block title %}Admin{% endblock %}

{% block body %}
<div class="row mt-5">
  <h1 class="text-center">
    Upload Questions
  </h1>
</div>
<div class="row mt-3">
  <form action="{{ url_for('main.admin_upload_questions') }}" method="post" enctype="multipart/form-data">
    <div class="mb-3">
      <label for="formFile" class="form-label">Upload CSV File.</label>
      <input class="form-control" type="file" accept=".csv" id="formFile" name="qFile" required>
    </div>
    <br>
    <button type="submit" class="btn btn-primary w-100">Upload</button>
  </form>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}Index{% endblock %}

{% block body %}
<div class="row">
  <p>Hello,</p>
</div>
<div class="row">
  <p>My name is Bittu and I am a passionate developer. Welcome to my quiz website!</p>
</div>
<div class="row">
  <p>Here, students have the opportunity to contribute their own questions and challenge other students. I believe that learning is not limited to textbooks, and by creating this platform, I aim to foster a collaborative and engaging environment for students to expand their knowledge. With the ability to add questions and participate in quizzes, students can actively participate in the learning process and test their understanding of various subjects.</p>
</div>
<div class="row">
  <p>Join me on this exciting journey of exploration and let's enhance our knowledge together. Feel free to reach out to me on my GitHub page at <a href="https://github.com/Dev-Bittu">Dev-Bittu</a> for any suggestions or feedback.</p>
  <p>Happy quizzing!</p>
</div>
<div class="row">
  <p>~<em>Bittu</em></p>
</div>
{% endblock %}

templates/layout.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet">
  <title>{% block title %}{% endblock %} | Quiz App</title>
  <link rel="icon" href="{{ url_for('static', filename='image/favicon.ico') }}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <img src="{{ url_for('static', filename='image/logo.png') }}" alt="" width="30" height="30" class="d-inline-block">
        QuizApp
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          {% if current_user.is_authenticated %}
          {% if current_user.is_admin %}
          <li class="nav-item">
            <a class="nav-link text-center" href="{{ url_for('main.admin') }}">Admin</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link text-center" href="{{ url_for('main.add_questions') }}">Add Questions</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-center" href="{{ url_for('main.quiz') }}">Quiz</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-center" href="{{ url_for('main.result') }}">Result</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-center" href="{{ url_for('main.leaderboard') }}">Leaderboard</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link text-center" href="{{ url_for('main.logout') }}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link text-center" href="{{ url_for('main.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-center" href="{{ url_for('main.register') }}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% for category, message in messages %}
  <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
    <strong>{{ category.upper() }}</strong> {{ message.title() }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}
  {% endwith %}
  <div class="container mt-5 mb-5">
    {% block body %}{% endblock %}
  </div>
<style>
.nav-link:hover{
    color: white;
    border-style: solid;
    background-color: blue;
    border-color: blue;
    border-radius: 13px;
}
.navbar .navbar-nav .nav-link {
  padding: 0.6em;
}
.navbar .navbar-brand {
  padding: 0 0.6em;
}
@media only screen and (min-width: 992px) {
  .navbar {
    padding: 0;
  }
  .navbar .navbar-nav .nav-link {
    padding: 1em 0.7em;
  }
  .navbar .navbar-brand {
    padding: 0 0.8em;

.navbar .navbar-nav .nav-link {
  padding: 1em 0.7em;
  transition: all 0.5s;
}
</style>
  <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
</body>
</html>

templates/leaderboard.html
{% extends 'layout.html' %}

{% block title %}Leaderboard{% endblock %}

{% block body %}
<div class="row">
  <h1 class="text-center">Leaderboard</h1>
</div>
<div class="row">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Rank</th>
      <th scope="col">Name</th>
      <th scope="col">Total Questions</th>
      <th scope="col">Not Attempt</th>
      <th scope="col">Correct</th>
      <th scope="col">Incorrect</th>
      <th scope="col">Total Marks</th>
    </tr>
  </thead>
  <tbody>
    {% for result in results %}
    <tr>
      <th scope="row">{{ loop.index }}</th>
      <td>{{ result.user.name }}</td>
      <td>{{ result.total_number }}</td>
      <td>{{ result.not_attempt }}</td>
      <td>{{ result.correct }}</td>
      <td>{{ result.incorrect }}</td>
      <td>{{ result.correct }}/{{ result.total_number }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

templates/login.html
{% extends 'layout.html' %}

{% block title %}Login{% endblock %}

{% block body %}
  <form method="post" action="{{ url_for('main.login') }}">
    <h1 class="text-center">Login</h1>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <input type="text" class="form-control" id="name" aria-describedby="nameHelp" name="name" placeholder="Name" required autofocus>
    <div id="nameHelp" class="form-text">We'll never share your name with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password" required>
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1" name="is_admin">
    <label class="form-check-label" for="exampleCheck1">Are you Admin?</label>
  </div>
  <button type="submit" class="btn btn-primary w-100">Submit</button>
</form>
{% endblock %}

templates/quiz.html
{% extends 'layout.html' %}
{% block title %}Quiz{% endblock %}
{% block body %}
<form method="post" action="{{ url_for('main.quiz') }}">
   <h1 class="text-center">
      Quiz
   </h1>
   {% for q in questions %}
  <div class="card border-info">
     <div class="card-header bg-info text-white">Question {{loop.index}}</div>
   <div class="card-body">
      <h5 class="user-select-none">{{ q.question }}</h5>
      <input type="hidden" name="q{{loop.index}}" value="{{q.id}}">
      <div class="form-check">
         <input class="form-check-input" type="radio" name="q{{loop.index}}o" id="q{{loop.index}}o1" value="A">
         <label class="form-check-label" for="q{{loop.index}}o1">
            {{ q.option1 }}
         </label>
      </div>
      <div class="form-check">
         <input class="form-check-input" type="radio" name="q{{loop.index}}o" id="q{{loop.index}}o2" value="B">
         <label class="form-check-label" for="q{{loop.index}}o2">
            {{ q.option2 }}
         </label>
      </div>
      <div class="form-check">
         <input class="form-check-input" type="radio" name="q{{loop.index}}o" id="q{{loop.index}}o3" value="C">
         <label class="form-check-label" for="q{{loop.index}}o3">
            {{ q.option3 }}
         </label>
      </div>
      <div class="form-check">
         <input class="form-check-input" type="radio" name="q{{loop.index}}o" id="q{{loop.index}}o4" value="D">
         <label class="form-check-label" for="q{{loop.index}}o4">
            {{ q.option4 }}
         </label>
      </div>
   </div>
   </div>
   <br>
   {% endfor %}
   <br>
   <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1" required>
    <label class="form-check-label" for="exampleCheck1">I confirmed.</label>
  </div>
  <br>
  <button type="submit" class="btn btn-primary w-100" {% if not show %}onclick="quiz_complete(); return false;"{% endif %}>Submit</button>
</form>
<script>
   const quiz_complete = () => {
      alert("You already done this quiz, you can't attempt any more.");
   }
</script>
{% endblock %}

templates/register.html
{% extends 'layout.html' %}

{% block title %}Register{% endblock %}

{% block body %}
<form method="post" action="{{ url_for('main.register') }}">
  <h1 class="text-center">
    Register
  </h1>
  <div class="mb-3">
    <label for="exampleInputName1" class="form-label">Name</label>
    <input type="text" class="form-control" id="exampleInputName1" aria-describedby="nameHelp" name="name" placeholder="Name" required autofocus>
    <div id="nameHelp" class="form-text">We'll never share your name with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password" required>
  </div>
  <button type="submit" class="btn btn-primary w-100">Submit</button>
</form>
{% endblock %}

templates/result.html
{% extends 'layout.html' %}

{% block title %}Result{% endblock %}

{% block body %}
  <h1 class="text-center">
    Result
  </h1>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Total Questions</th>
      <th scope="col">Not Attempt</th>
      <th scope="col">Correct</th>
      <th scope="col">Incorrect</th>
      <th scope="col">Total Marks</th>
    </tr>
  </thead>
  <tbody>
    {% for result in results %}
    <tr>
      <th scope="row">{{ result.id }}</th>
      <td>{{ user.name }}</td>
      <td>{{ result.total_number }}</td>
      <td>{{ result.not_attempt }}</td>
      <td>{{ result.correct }}</td>
      <td>{{ result.incorrect }}</td>
      <td>{{ result.incorrect }}/{{ result.total_number }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}